import React from 'react';
import { GridColDef } from '@mui/x-data-grid-pro';
import { renderHeader } from './utils/renderHeader';
import { getNumberFilterOperations, getDateTimeFilterOperations } from 'utils/search';
import { renderUser, renderDateTime } from './utils/renderer';

const columns: GridColDef[] = [
    {
        field: 'id',
        headerName: 'ID',
        description: 'id',
        flex: 1,
        resizable: true,
        minWidth: 120,
        renderHeader,
        filterOperators: getNumberFilterOperations(),
    },
    {
        field: 'status',
        headerName: 'Status',
        description: 'status',
        flex: 1,
        resizable: true,
        minWidth: 170,
        renderHeader,
        filterOperators: getNumberFilterOperations(),
    },
    {
        field: 'addedCount',
        headerName: 'Added Count',
        description: 'addedCount',
        flex: 1,
        resizable: true,
        minWidth: 170,
        renderHeader,
        filterOperators: getNumberFilterOperations(),
    },
    {
        field: 'updatedCount',
        headerName: 'Updated Count',
        description: 'updatedCount',
        flex: 1,
        resizable: true,
        minWidth: 170,
        renderHeader,
        filterOperators: getNumberFilterOperations(),
    },
    {
        field: 'deletedCount',
        headerName: 'Deleted Count',
        description: 'deletedCount',
        flex: 1,
        resizable: true,
        minWidth: 170,
        renderHeader,
        filterOperators: getNumberFilterOperations(),
    },
    {
        field: 'errorMessage',
        headerName: 'Error Message',
        description: 'errorMessage',
        flex: 1,
        resizable: true,
        minWidth: 200,
        type: 'string',
        filterable: false,
        sortable: false,
    },
    {
        field: 'createdBy',
        headerName: 'Created By',
        description: 'createdBy',
        flex: 1,
        resizable: true,
        minWidth: 200,
        type: 'string',
        filterable: false,
        sortable: false,
        renderCell: renderUser,
    },
    {
        field: 'createdAt',
        headerName: 'Created At',
        description: 'createdAt',
        flex: 1,
        resizable: true,
        minWidth: 220,
        type: 'dateTime',
        renderHeader,
        filterOperators: getDateTimeFilterOperations(),
        renderCell: renderDateTime,
    },
];
