version: '3.7'

services:
  lab1-client:
    container_name: lab1-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
jest:
  config:
    js:
